// REST Client
// https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@url=http://localhost:{{$dotenv API_PORT}}/api

### GET healthcheck
GET {{url}}/healthcheck

### GET owner by id
GET {{url}}/owners/1

### GET nearest owner
GET {{url}}/owners?long=-43.297110&lat=-23.013538

### GET nearest owner
GET {{url}}/owners?long=-46.772907&lat=-23.528173

### POST owner
POST {{url}}/owners
Content-Type: application/json

{
  "id": 110,
  "tradingName": "Adega da Cerveja - Pinheiros",
  "ownerName": "Zé da Silva",
  "document": "1432132123891/0101",
  "coverageArea": {
    "type": "MultiPolygon",
    "coordinates": [
      [[[30, 20], [45, 40], [10, 40], [30, 20]]],
      [[[15, 5], [40, 10], [10, 20], [5, 10], [15, 5]]]
    ]
  },
  "address": {
    "type": "Point",
    "coordinates": [-46.57421, -21.785741]
  }
}